import type { Device } from "../utils/devices";

type VectorEntry = { irq: number; name: string; desc: string; category: string; defaultAddr: string };

export default function InterruptViewerView({
  device,
  onNavigate,
}: {
  device: Device;
  onNavigate?: (view: any, parameter?: string) => void;
}) {
  if (!device) return null;

  const baseVector = device.vectorTableAddr || 0x08000000;

  const VECTORS: VectorEntry[] = [
    { irq: -15, name: "Reset_Handler", desc: "System Reset Vector Executed upon power-on or hardware reset pin toggle.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x04).toString(16)}` },
    { irq: -14, name: "NMI_Handler", desc: "Non-Maskable Interrupt generated by clock security system or external hardware fail.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x08).toString(16)}` },
    { irq: -13, name: "HardFault_Handler", desc: "Hard Fault exception triggered on illegal instruction execution or invalid memory access.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x0c).toString(16)}` },
    { irq: -12, name: "MemManage_Handler", desc: "Memory Protection Unit (MPU) fault vector triggered on access violation.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x10).toString(16)}` },
    { irq: -11, name: "BusFault_Handler", desc: "Bus fault vector triggered on AHB/APB bus transaction error or unaligned access.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x14).toString(16)}` },
    { irq: -10, name: "UsageFault_Handler", desc: "Usage fault exception triggered on divide-by-zero or undefined instruction execution.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x18).toString(16)}` },
    { irq: -5, name: "SVC_Handler", desc: "SuperVisor Call exception triggered by 'svc' assembly instruction for RTOS system calls.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x2c).toString(16)}` },
    { irq: -2, name: "PendSV_Handler", desc: "Pending Supervisor Call exception used by RTOS for context switching between threads.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x38).toString(16)}` },
    { irq: -1, name: "SysTick_Handler", desc: "24-bit System Tick timer interrupt generating time base tick for RTOS scheduler.", category: "System Exception", defaultAddr: `0x${(baseVector + 0x3c).toString(16)}` },
    { irq: 0, name: "WWDG_IRQHandler", desc: "Window Watchdog Interrupt triggered before watchdog resets MCU.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0x40).toString(16)}` },
    { irq: 1, name: "PVD_IRQHandler", desc: "Programmable Voltage Detector interrupt triggered on supply voltage dip.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0x44).toString(16)}` },
    { irq: 6, name: "EXTI0_IRQHandler", desc: "External Interrupt Line 0 handler for GPIO pin state changes.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0x58).toString(16)}` },
    { irq: 11, name: "DMA1_Channel1_IRQHandler", desc: "Direct Memory Access Channel 1 transfer complete or error interrupt.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0x6c).toString(16)}` },
    { irq: 18, name: "ADC1_2_IRQHandler", desc: "Analog to Digital Converter 1 & 2 conversion complete interrupt vector.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0x88).toString(16)}` },
    { irq: 37, name: "USART1_IRQHandler", desc: "Universal Synchronous Asynchronous Receiver Transmitter 1 RX/TX interrupt.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0xd4).toString(16)}` },
    { irq: 38, name: "USART2_IRQHandler", desc: "USART 2 interrupt handler.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0xd8).toString(16)}` },
    { irq: 42, name: "SPI1_IRQHandler", desc: "Serial Peripheral Interface 1 transmit buffer empty / receive data ready vector.", category: "Peripheral IRQ", defaultAddr: `0x${(baseVector + 0xe8).toString(16)}` },
  ];

  return (
    <div className="p-6 h-full overflow-y-auto space-y-6 bg-[var(--bg)] text-white mono text-xs select-none">
      {/* HEADER */}
      <div className="pb-4 border-b border-[var(--line)] flex justify-between items-center">
        <div>
          <div className="text-[10px] text-[var(--mut)] uppercase tracking-wider font-bold">Device Support System</div>
          <h1 className="text-xl font-bold text-white">Interrupt Vector Table Viewer</h1>
        </div>
        <div className="text-right">
          <div className="text-[10px] text-[var(--mut)] uppercase">Target Profile</div>
          <div className="text-sm font-bold text-[var(--a)]">{device.name}</div>
        </div>
      </div>

      {/* VECTOR TABLE GRID */}
      <div className="p-5 rounded-xl bg-black/30 border border-[var(--line)] space-y-4">
        <div className="flex justify-between items-center">
          <h2 className="text-sm font-bold text-white">Vector Table Layout & Interrupt Handlers</h2>
          <span className="text-[10px] text-purple-400 font-mono">Base: 0x{baseVector.toString(16)}</span>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse text-[11px]">
            <thead>
              <tr className="border-b border-[var(--line)] text-[var(--mut)] uppercase text-[10px]">
                <th className="py-2.5 px-3">IRQ Num</th>
                <th className="py-2.5 px-3">Handler Symbol</th>
                <th className="py-2.5 px-3">Category</th>
                <th className="py-2.5 px-3">Vector Address</th>
                <th className="py-2.5 px-3">Description</th>
                <th className="py-2.5 px-3">Action</th>
              </tr>
            </thead>
            <tbody>
              {VECTORS.map(v => (
                <tr key={v.name} className="border-b border-[var(--line)]/40 hover:bg-white/5 transition">
                  <td className="py-3 px-3 font-mono font-bold text-amber-300">{v.irq}</td>
                  <td className="py-3 px-3 font-bold text-white">{v.name}</td>
                  <td className="py-3 px-3 text-[10px]">
                    <span className={`px-2 py-0.5 rounded border ${v.category === "System Exception" ? "bg-purple-500/10 text-purple-300 border-purple-500/20" : "bg-emerald-500/10 text-emerald-300 border-emerald-500/20"}`}>
                      {v.category}
                    </span>
                  </td>
                  <td className="py-3 px-3 font-mono text-purple-400">{v.defaultAddr}</td>
                  <td className="py-3 px-3 text-gray-300 text-[10px]">{v.desc}</td>
                  <td className="py-3 px-3">
                    <button
                      onClick={() => onNavigate?.("investigator", v.name)}
                      className="px-2 py-1 rounded bg-[var(--a-dim)] text-[var(--a)] border border-[var(--a-dim)] hover:bg-[var(--a)] hover:text-black font-bold text-[10px] transition"
                    >
                      Investigate Code
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
